### ISSUE TITLE
по разному все выглядит в ie7 ie8

### ISSUE THREAD

**Issue by kturichev** [agat/css-framework#7]
Здравствуйте, планируется ли дорабатывать стили для ie7 и ie8? А то выглядит не очень красиво.

**Comment by agat** [comment]
Для реализации всех возможностей дизайна в старых версиях IE существует множество способов(к примеру http://css3pie.com/ или http://code.google.com/p/ie7-js/).
Какой способ выбрать - очень сильно зависит от проекта и выбирается индивидуально.
В задачу проекта не входит усложнение кода такими вот костылями.
